project:
  type: website

website:
  title: "PVA"
  page-footer: 
    right: "This page is built with [Quarto](https://quarto.org/) ❤️"
  
  site-url: https://martinekpavel.github.io/vyuka/
  repo-url: https://github.com/martinekpavel/vyuka
  repo-actions: [edit, source, issue]  
  
  navbar:
    left:
      #  - href: index.qmd
      #    text: Úvod
      - href: 202526-1d.qmd
        text: "1.D 2025/26"
      - href: 202526-3d.qmd
        text: "3.D 2025/26"
      - href: web_html/index.qmd
        text: "HTML"
      - text: "Algoritmy"
        href: web_algo/index.qmd
      - text: "Python"
        href: web_python/index.qmd
      - text: "JavaScript"
        href: web_js/index.qmd
      - about.qmd

  sidebar:
    - title: "HTML"
      style: "docked"
      # background: light
      contents:
        - web_html/index.qmd
        - web_html/01uvod.qmd
        - web_html/02git.qmd
        - web_html/03html.qmd
        - web_html/04publish.qmd
        - web_html/05css.qmd
        - web_html/06menu.qmd
        - web_html/07mediaq.qmd
        - web_html/08portfolio.qmd
        - web_html/09search.qmd
        - web_html/10rekap.qmd
        - web_html/11projekt.qmd
        - web_html/12search.qmd
        - web_html/13webai.qmd    
    - title: "JavaScript"
      style: "docked"
      contents:
            - web_js/index.qmd
            - web_js/01lekcejs.qmd
    - title: "Algoritmy"
      style: "docked"
      contents:
            - web_algo/index.qmd
    - title: "Python"
      style: "docked"
          # background: light
      contents:
            - web_python/index.qmd

format:
  html:
    theme: 
      light: yeti
      dark: superhero
    # theme: [sandstone, custom.scss]
    css: styles.css
    toc: true
    # toc-title: Contents
    toc-location: right

lang: cs

# quarto publish gh-pages

